name: Generate Heatmap

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 指定 Python 版本

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装依赖

      # 4. 设置环境变量
      - name: Set environment variables
        env:
          GITHUB_USERNAME: ${{ secrets._GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          GITHUB_API_HOST: ${{ secrets._GITHUB_API_HOST }}
          GITLAB_USER_ID: ${{ secrets._GITLAB_USER_ID }}
          GITLAB_TOKEN: ${{ secrets._GITLAB_TOKEN }}
          GITLAB_API_HOST: ${{ secrets._GITLAB_API_HOST }}
        run: |
          echo "GITHUB_USERNAME=$GITHUB_USERNAME" >> .env
          echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> .env
          echo "GITHUB_API_HOST=$GITHUB_API_HOST" >> .env
          echo "GITLAB_USER_ID=$GITLAB_USER_ID" >> .env
          echo "GITLAB_TOKEN=$GITLAB_TOKEN" >> .env
          echo "GITLAB_API_HOST=$GITLAB_API_HOST" >> .env

      # 5. 运行脚本生成热力图
      - name: Generate heatmap
        run: |
          python main.py  # 运行你的脚本

      # 6. 上传生成的热力图作为 Artifact
      - name: Upload heatmap as artifact
        uses: actions/upload-artifact@v4
        with:
          name: heatmap
          path: heatmap.png  # 热力图文件路径

      # 7. 上传生成的热力图原始数据
      - name: Upload heatmap_data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: heatmap_data
          path: merged_contributions.csv  # 数据文件路径