name: Generate Heatmap

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装中文字体
      - name: Install Chinese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      # 3. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 指定 Python 版本

      # 4. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装依赖

      # 5. 设置环境变量
      - name: Set environment variables
        env:
          GITHUB_USERNAME: ${{ secrets._GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          GITHUB_API_HOST: ${{ secrets._GITHUB_API_HOST }}
          GITLAB_USER_ID: ${{ secrets._GITLAB_USER_ID }}
          GITLAB_TOKEN: ${{ secrets._GITLAB_TOKEN }}
          GITLAB_API_HOST: ${{ secrets._GITLAB_API_HOST }}
          EXPAND_DAYS: ${{ secrets._EXPAND_DAYS }}
        run: |
          echo "_GITHUB_USERNAME=$GITHUB_USERNAME" >> .env
          echo "_GITHUB_TOKEN=$GITHUB_TOKEN" >> .env
          echo "_GITHUB_API_HOST=$GITHUB_API_HOST" >> .env
          echo "_GITLAB_USER_ID=$GITLAB_USER_ID" >> .env
          echo "_GITLAB_TOKEN=$GITLAB_TOKEN" >> .env
          echo "_GITLAB_API_HOST=$GITLAB_API_HOST" >> .env
          echo "_EXPAND_DAYS=$EXPAND_DAYS" >> .env

      # 6. 运行脚本生成热力图
      - name: Generate heatmap
        run: |
          python main.py  # 运行你的脚本

      # 7. 上传生成的热力图和原始数据作为 Artifact
      - name: Upload heatmap and data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: heatmap_and_data
          path: |
            heatmap.png  # 热力图文件路径
            merged_contributions.csv  # 数据文件路径